#
#
# Any python errors about python not found
# install the python-is-python3 package

ESP_ROOT := esp8266
CHIP := esp8266
BOARD := d1_mini
BUILD_DIR := ./build/$(BOARD)

ESPTOOL := $(ESP_ROOT)/tools/esptool/esptool.py

#FLASH_SPEED := 40m
#FLASH_MODE := dio

SKETCH := wled00/wled00.ino
FS_DIR := wled00/data

EXCLUDE_DIRS := usermods/
CUSTOM_LIBS := lib

BUILD_EXTRA_FLAGS += -Iwled00
BUILD_EXTRA_FLAGS += -Ilib/ESPAsyncTCP
BUILD_EXTRA_FLAGS += -Ilib/ESPAsyncTCP/src
BUILD_EXTRA_FLAGS += -Ilib/ESPAsyncWebServer/src
BUILD_EXTRA_FLAGS += -Ilib/ESPAsyncUDP/src
BUILD_EXTRA_FLAGS += -Ilib/FastLED/src
BUILD_EXTRA_FLAGS += -Ilib/NeoPixelBus/src

BUILD_EXTRA_FLAGS += -DWLED_DISABLE_INFRARED
#BUILD_EXTRA_FLAGS += -DWLED_DISABLE_MQTT
#BUILD_EXTRA_FLAGS += -DWLED_DISABLE_LOXONE
#BUILD_EXTRA_FLAGS += -DWLED_DISABLE_WEBSOCKETS
#BUILD_EXTRA_FLAGS += -DWLED_DISABLE_BLYNK
#BUILD_EXTRA_FLAGS += -DWLED_USE_REAL_MATH
#BUILD_EXTRA_FLAGS += -DESP8266 -DFP_IN_IROM -DLEDPIN=12 -DIRPIN=-1 -DRLYPIN=2

BUILD_EXTRA_FLAGS += -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_190703
BUILD_EXTRA_FLAGS += -DPIO_FRAMEWORK_ARDUINO_LWIP_HIGHER_BANDWIDTH
BUILD_EXTRA_FLAGS += -DVTABLES_IN_FLASH
BUILD_EXTRA_FLAGS += -DMIMETYPE_MINIMAL

#BUILD_EXTRA_FLAGS += -DMQTT_MAX_PACKET_SIZE=1024
#BUILD_EXTRA_FLAGS += -DSECURE_CLIENT=SECURE_CLIENT_BEARSSL
#BUILD_EXTRA_FLAGS += -DBEARSSL_SSL_BASIC
BUILD_EXTRA_FLAGS += -DCORE_DEBUG_LEVEL=0
BUILD_EXTRA_FLAGS += -DNDEBUG
#BUILD_EXTRA_FLAGS += -D_IR_ENABLE_DEFAULT_=false
#BUILD_EXTRA_FLAGS += -DDECODE_HASH=true
#BUILD_EXTRA_FLAGS += -DDECODE_NEC=true
#BUILD_EXTRA_FLAGS += -DDECODE_SONY=true
#BUILD_EXTRA_FLAGS += -DDECODE_SAMSUNG=true
#BUILD_EXTRA_FLAGS += -DDECODE_LG=true
#BUILD_EXTRA_FLAGS += -DWLED_USE_MY_CONFIG

include makeEspArduino/makeEspArduino.mk

$(SKETCH): $(BUILD_DIR)/build_opt.h

# Another bug work around
$(ESP_ROOT)/tool/esptool.py: $(CHIP)/tool/esptool/esptool.py
	ln -sf $< $@

$(BUILD_DIR)/build_opt.h: build_opt.h
	cp $< $@

$(notdir $(SKETCH)).cpp: $(SKETCH)
	cp $< $@

